### ISSUE TITLE
Upgrade to kernel +4.x

### ISSUE THREAD

**Issue by gnzlbg** [sabotage-linux/kernel-headers#15]
Are there musl sanitized versions of the latest kernel headers ? E.g. the ones shipped with Ubuntu 19.04 ?

**Comment by rofl0r** [comment]
currently not. is there something missing in particular that you need? if not, there should be no issue with using the ones we ship.

**Comment by gnzlbg** [comment]
`MAP_FIXED_NOREPLACE`, among many others, but I can compile a comprehensive List if you want.

**Comment by gnzlbg** [comment]
Basically we ship Rust musl targets with the headers here, and while our Rust gnu targets supports up-to kernel 5.x features, our musl ones do not.

**Comment by rofl0r** [comment]
i pushed a tag for kernel 4.4.2-based headers, plus a number of regression tests. seems to work fine so far (i did a testbuild of a good portion of sabotage's packages against it).
i also tried with a much newer kernel, however there were a lot of internal inconsistencies, so i opted for a smaller jump for the time being. in number of major kernel version bumps, this is roughly half way between where we were and 5.x.

**Comment by gnzlbg** [comment]
> i pushed a tag for kernel 4.4.2-based headers, plus a number of regression tests. seems to work fine so far (i did a testbuild of a good portion of sabotage's packages against it).

@rofl0r thank you! I'll upgrade our musl builders to start using that, and once we finish some internal refactorings, we should end up with a documented list of what exactly (if anything) are we still missing.

> i also tried with a much newer kernel, however there were a lot of internal inconsistencies, so i opted for a smaller jump for the time being.

Makes sense. For us it is also good to do these updates incrementally.

**Comment by copy** [comment]
Another update would be nice, e.g. for `struct clone_args`.
